  # HTTP : Redirection automatique vers le HTTPS
  server {
      listen 80;
      server_name worldbuilding.molternate.com;

      # Laisse passer les vérifications LetsEncrypt
      location /.well-known/acme-challenge/ {
          root /var/www/certbot;
      }

      # Redirige vers le HTTPS
      location / {
          return 301 https://$host$request_uri;
      }
  }

  # HTTPS
  server {
      listen 443 ssl;
      http2 on; # activer le HTTP2 (HTTPS)

      server_name worldbuilding.molternate.com;

      # Certificats SSL LetsEncrypt
      ssl_certificate /etc/letsencrypt/live/worldbuilding.molternate.com/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/worldbuilding.molternate.com/privkey.pem;

      # on affiche pas la version de nginx pour des raisons de sécurité
      server_tokens off;

      # Empeche l'accès aux dotfiles (.env, .git, etc.) et redirige vers l'accueil
      location ~ (^|/)\.(?!well-known)(?!vite).* {
          return 302 https://$http_host/;
      }

      # API Backend
      location ^~ /api/ {
          proxy_pass http://backend:80;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      # Application Frontend
      location / {
          proxy_pass http://frontend:80;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
  }
